api/urls.py
from django.conf.urls import url, include
import api.views as views


urlpatterns = [
    # url(r'^$', service_views.index, name='index'),
    url(r'^ip_hostname/(?P<ip>[\d\.]+)$', views.ip_to_hostname, name='ip_hostname'),
    url(r'^kpi_ding/$', views.kpi_ding, name='kpi_ding'),

]

ntdeploy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include('server.urls', namespace='server')),
    url(r'^options/', include('options.urls', namespace='options')),
    url(r'^grid/', include('grid.urls', namespace='grid')),
    url(r'^operating/', include('operating.urls', namespace='operating')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout),

    # url(r'^accounts/login/$', login, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
]

server/urls.py
# coding=utf-8
from django.conf.urls import url, include
import server.views as server_views
import server.views_domain as domain_views
import cmdb.views as cmdb_views

urlpatterns = [
    # url(r'^$', server_views.index, name='index'),
    url(r'^page/', server_views.page, name='page'),
    url(r'^page_enabled/', server_views.page_enabled, name='page_enabled'),
    url(r'^upload/', server_views.upload, name='upload'),
    url(r'^add/', server_views.add, name='add'),
    url(r'^update/(?P<srv_id>\d+)/', server_views.update, name='update'),
    # url(r'^remove/', server_views.remove_server, name='remove'),
    url(r'^search_by_area/', server_views.search_by_area, name='search_by_area'),
    url(r'^view_log/(?P<srv_id>\d+)/', server_views.view_log, name='view_log'),
    url(r'^connect/(?P<srv_id>\d+)/', server_views.connect, name='connect'),

    # domain urls
    url(r'^domain/$', domain_views.index, name='domain_index'),
    url(r'^domain/page/', domain_views.page, name='domain_page'),
    url(r'^domain/add/', domain_views.add, name='domain_add'),
    url(r'^domain/update/(?P<dmn_id>\d+)/', domain_views.update, name='domain_update'),
    url(r'^domain/remove/', domain_views.remove, name='domain_remove'),
    url(r'^domain/upload/', domain_views.upload, name='domain_upload'),

    # cmdb
    url(r'^$', cmdb_views.service_info, name='index'),
    url(r'^index_phone', cmdb_views.service_info_phone, name='index_phone'),
    url(r'^update_info/', cmdb_views.update_info, name='update_info'),
    url(r'^job_list_page/', cmdb_views.job_list_page, name='job_list_page'),
    url(r'^job_list_page_phone/', cmdb_views.job_list_page_phone, name='job_list_page_phone'),
    url(r'^eip_page/', cmdb_views.eip_page, name='eip_page'),
    url(r'^export/', cmdb_views.export, name='export'),
    url(r'^show_del_server/', cmdb_views.show_del_server, name='show_del_server'),
    url(r'^del_list_page/', cmdb_views.del_list_page, name='del_list_page'),
    url(r'^update_status_page/', cmdb_views.update_status_page, name='update_status_page'),
    url(r'^show_update_info/', cmdb_views.show_update_info, name='show_update_info'),
    url(r'^do_operate/', cmdb_views.do_operate, name='do_operate'),
    url(r'^add_server/', cmdb_views.add_server, name='add_server'),
    url(r'^check_ssh_copy/', cmdb_views.check_ssh_copy, name='check_ssh_copy'),
    url(r'^services/', cmdb_views.restart_service, name='restart_service'),

    url(r'^modify/(?P<srv_id>\d+)/', cmdb_views.modify, name='modify'),
    url(r'^deeply_delete/', cmdb_views.deeply_delete, name='deeply_delete'),

    url(r'^group/', cmdb_views.group_index, name='group'),
    url(r'^eip/', cmdb_views.eip_index, name='eip'),
    url(r'^group_page/', cmdb_views.group_page, name='group_page'),
    url(r'^add_group/', cmdb_views.add_group, name='add_group'),
    url(r'^get_servers/', cmdb_views.get_servers, name='get_servers'),
    url(r'^update_group/(?P<gid>\d+)/', cmdb_views.update_group, name='update_group'),
    url(r'^remove_group/', cmdb_views.remove_group, name='remove_group'),

    # api
    url(r'^add_server_api/', cmdb_views.add_server_api, name='add_server_api'),
    url(r'^route_shell/', cmdb_views.route_shell, name='route_shell'),

]

cmdb/forms.py
#!/usr/bin/python
# coding:utf-8
__author__ = 'Fengxu'
from django import forms


class FileForm(forms.Form):
    upload_file = forms.FileField()


class AddServer(forms.Form):
    id = forms.IntegerField(required=False)
    # name = forms.CharField(max_length=20)
    inner_ip = forms.CharField(required=False, max_length=16)
    outer_ip = forms.CharField(required=False, max_length=16)
    area = forms.CharField(max_length=40)
    user = forms.CharField(max_length=20)
    password = forms.CharField(max_length=40)
    port = forms.IntegerField(required=False)
    sn = forms.CharField(required=False)
    remark = forms.CharField(required=False)


class AddDomain(forms.Form):
    id = forms.IntegerField(required=False)
    type = forms.CharField()
    domain = forms.CharField(max_length=80)
    ip = forms.CharField(max_length=16)
    category = forms.IntegerField()
    remark = forms.CharField(max_length=40, required=False)


class AddServerApiForm(forms.Form):
    innerIp = forms.CharField(max_length=40, required=False)
    publicIp = forms.CharField(max_length=40, required=False)
    user = forms.CharField(max_length=40, required=False)
    port = forms.IntegerField(required=False)
    kw = forms.CharField(required=False)


def main():
    pass


if __name__ == "__main__":
    main()

templates/domain/add-result.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {{ message.title }}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:domain_index' %}"><i class="fa fa-server"></i> 域名-IP列表</a></li>
                    <li><a href="{% url 'server:domain_add' %}"><i class="fa fa-server"></i> 添加域名-IP映射</a></li>
                    <li class="active">{{ message.title }}</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">{{ message.message }}</h3>

                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <a href="{% url 'server:domain_index' %}">点击转到域名-IP列表</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}

templates/domain/add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}配置管理系统_V1.0.0{% endblock %}
{% block css %}

{% endblock %}

{% block body %}


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {% if domain %}更新{% else %}添加{% endif %}域名-IP映射
{#                    <small>控制面板</small>#}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:domain_index' %}"><i class="fa fa-server"></i> 域名-IP列表</a></li>
                    <li class="active">添加域名-IP映射</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            {% comment %}<div class="box-header">
                                <h3 class="box-title">Server</h3>
                                <button type="button" id="button">点击获取</button>

                            </div>{% endcomment %}<!-- /.box-header -->
                            <div class="box-body">
                                <div id="tips">
                                {% if message and message.result == False %}
                                <div class="alert alert-danger"><strong>添加失败：</strong>{{ message.message }}</div>
                                {% endif %}
                                </div>
                                <form id="server_form" class="form-horizontal" role="form" action="{% if domain %}{% url 'server:domain_update' dmn_id=domain.id %}{% else %}{% url 'server:domain_add' %}{% endif %}" method="post" onsubmit="return validate()">
                                    <input id="id_id" name="id" type="hidden" value="{{ domain.id }}"/>
                                    <input name="type" type="hidden" value="{% if domain %}update{% else %}add{% endif %}"/>
                                    {% csrf_token %}
                                  <div class="form-group">
                                    <label for="id_domain" class="col-sm-2 control-label">域名</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_domain" name="domain" placeholder="域名" required
                                             value="{% if domain %}{{ domain.domain }}{% else %}{% if message %}{{ message.data.domain }}{% endif %}{% endif %}">
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <label for="id_category" class="col-sm-2 control-label">IP类型</label>
                                    <div class="col-sm-10">
                                        <select class="form-control" name="category" id="id_category" {% if domain %} readonly{% endif %}>
                                            {% if domain %}
                                                <option value="{{ domain.category }}">{% if domain.category == 0 %}内网IP{% else %}外网IP{% endif %}</option>
                                            {% else %}
                                                <option value="0" {% if message.data.category == 0 %} selected{% endif %}>内网IP</option>
                                                <option value="1" {% if message.data.category == 1 %} selected{% endif %}>外网IP</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                  </div>
                                    <div class="form-group">
                                    <label for="id_ip" class="col-sm-2 control-label">IP地址</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_ip" name="ip" placeholder="IP地址"
                                             value="{% if domain %}{{ domain.ip }}{% else %}{% if message %}{{ message.data.ip }}{% endif %}{% endif %}" required {% if domain %} readonly{% endif %}>
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <label for="id_remark" class="col-sm-2 control-label">备注</label>
                                    <div class="col-sm-10">
                                      <textarea id="id_remark" class="form-control" rows="3" name="remark">{% if domain %}{{ domain.remark }}{% else %}{% if message %}{{ message.data.remark }}{% endif %}{% endif %}</textarea>
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                      <button type="submit" class="btn btn-primary">{% if domain %}更新{% else %}添加{% endif %}域名-IP映射</button>
                                    </div>
                                  </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}
{% block script %}
    <script>
    function validate(){

    }
    </script>
{% endblock %}

templates/domain/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load data_option_tags %}
{% block css %}
{#    <link rel="stylesheet" href="{% static "admin_lte/plugins/datatables/jquery.dataTables.min.css" %}">#}
    <link rel="stylesheet" href="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.css" %}">
    <style type="text/css">
    table.dataTable tbody tr.selected {
        background-color: #B0BED9;
    }
    table.dataTable.row-border tbody th, table.dataTable.row-border tbody td, table.dataTable.display tbody th, table.dataTable.display tbody td {
        border-top: 1px solid #ddd;
        line-height: 35px;
    }
    </style>
{% endblock %}

{% block body %}


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    域名-IP列表
{#                    <small>控制面板</small>#}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li class="active">域名-IP列表</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <form class="form-inline" action="javascript:void(0);" id="search_form" role="form" style="margin-bottom: 20px;">
                                  <div class="form-group">
                                    <label class="sr-only" for="id_kw">关键字</label>
                                    <input type="text" class="form-control fa fa-dashboard" id="id_kw" name="kw" placeholder="搜索域名/IP/主机名">
                                  </div>
                                  <div class="form-group">
                                      <div class="btn-group" id="ip_category_btns">
                                          <button type="button" class="btn btn-default btn-primary" data-value="2">全部</button>
                                          <button type="button" class="btn btn-default" data-value="0">内网</button>
                                          <button type="button" class="btn btn-default" data-value="1">外网</button>
                                      </div>
                                  </div>
                                  <div class="form-group">
                                    <label class="sr-only" for="area_select">机房</label>

                                    <select id="area_select" name="area" class="form-control">
                                      <option value="">机房-全部</option>
                                      {% data_option 'area' %}
                                    </select>
                                  </div>
                                  <button type="submit" id="search_submit" class="btn btn-default">搜索</button>
                                </form>
                                <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'server:domain_add' %}'">添加</button>
                                <button type="button" class="btn btn-primary" id="batch_delete">删除</button>
                                <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'server:domain_upload' %}'">导入</button>

                            </div><!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <table id="example" class="display table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>操作</th>
                                        <th>域名</th>
                                        <th>IP类型</th>
                                        <th>IP地址</th>
                                        <th>主机名</th>
                                        <th>机房</th>
                                        <th>备注</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}
{% block script %}
    <script src="{% static "admin_lte/plugins/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.min.js"%}"></script>
    <script>

        $(function(){
            var $table = $("#example");
            var table = $table.DataTable({
                "bFilter": false,//去掉搜索框
                //"bAutoWidth": true, //自适应宽度
                "sPaginationType" : "full_numbers",
                //"sAjaxDataProp" : "aData",
                "bDestroy" : true,
                "bProcessing" : true,
                "iDisplayLength": 10,
                "sAjaxSource" : "{% url 'server:domain_page' %}?",
                "bServerSide" : true,

                "columns" : [
                    { 'data': null},
                    { 'data': 'id', "bSortable":false },
                    { "data" : "domain" },
                    { "data" : "category" },
                    { "data" : "ip" },
                    { "data" : "server", "bSortable":false  },
                    { "data" : "server", "bSortable":false  },
                    { "data" : "remark", "bSortable":false  }
                ],
                "columnDefs": [
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets":0
                         // "visible": false,
                    },
                    {
                    "targets": 1,//操作
                    "render": function(data, type, row, meta) {
                        return "<button class='btn btn-default domain-update' type='button' data-id='"+data+"'><i class='fa fa-edit'></i></button>" +
                                "&nbsp;&nbsp;<button class='btn btn-default server-delete' type='button' data-id='"+data+"'><i class='fa fa-trash-o'></i></button>"
                        }
                    },
                    {
                    "targets": -3,//操作
                    "render": function(data, type, row, meta) {
                        if(data != null){
                            return data.hostname;
                        }else{
                            return "—"
                        }
                        }
                    },
                    {
                    "targets": -2,//操作
                    "render": function(data, type, row, meta) {
                        if(data != null){
                            return data.area;
                        }else{
                            return "—"
                        }
                        }
                    },
                    {
                        "render": function(data, type, row, meta) {
                            switch(data){
                            case 0: return "内网";
                            case 1: return "外网";
                            }
                        },
                        //
                        "targets": 3
                    }
                ],
                "order": [[ 2, 'asc' ]],

                "oLanguage" : {
                    "sProcessing" : "正在加载中......",
                    "sLengthMenu" : "每页显示 _MENU_ 条记录",
                    "sZeroRecords" : "没有数据！",
                    "sEmptyTable" : "表中无数据存在！",
                    "sInfo" : "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
                    "sInfoEmpty" : "显示0到0条记录",
                    "sInfoFiltered" : "数据表中共为 _MAX_ 条记录",
                    //"sSearch" : "搜索",
                    "oPaginate" : {
                        "sFirst" : "首页",
                        "sPrevious" : "上一页",
                        "sNext" : "下一页",
                        "sLast" : "末页"
                    }
                }
            });
            // 选中操作
            table.on( 'click', 'tr[role="row"]', function () {
                $(this).toggleClass('selected');
            } );
            // 添加序号
            table.on( 'order.dt search.dt', function () {
                table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                    cell.innerHTML = i+1;
                } );
            } ).draw();

            function batch_delete(domain_ids){
                simple_ajax({
                    url: "{% url 'server:domain_remove' %}",
                    data:{"id": domain_ids},
                    // traditional:true,
                    success:function(data){
                        table.ajax.reload()
                    }
                })
            }

            $("#batch_delete").click(function(){
                // console.log(table.rows('.selected').data())
                var datas = table.rows('.selected').data();
                var length = datas.length;
                if(length > 0){
                    if(confirm("您确定要删除这" + length + "个域名-IP映射吗？")){
                        var server_ids = [];
                        for(var i=0; i<length; i++){
                            server_ids.push(datas[i].id);
                        }
                        batch_delete(server_ids)
                    }
                }else{
                    alert('请至少选择一个域名');
                }
            });
            $table.delegate('.server-delete', 'click', function(){
                if(confirm("您确定要删除该域名-IP映射吗？")){
                    batch_delete([$(this).attr("data-id")])
                }
            });
            $table.delegate('.domain-update', 'click', function(){
                window.location.href = '/server/domain/update/' + $(this).attr("data-id") + '/';
            });
            $("#search_form").submit(function(){
                var search_query = $(this).serialize() + "&category=" + $("#ip_category_btns").find("button.btn-primary").attr("data-value");
                table.ajax.url("{% url 'server:domain_page' %}?" + search_query).load();
                return false;
            });
            // 设置单选按钮组的class样式
            $("#ip_category_btns").find("button").click(function(){
                if(!$(this).hasClass("btn-primary")){
                    $(this).addClass("btn-primary").siblings().removeClass("btn-primary");
                }
            });
        })
    </script>
{% endblock %}

templates/domain/upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}配置管理系统_V1.0.0{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.css" %}">
{% endblock %}

{% block body %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    域名-IP列表
{#                    <small>控制面板</small>#}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li class="active">域名-IP列表</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">域名-IP数据导入</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">

                                <form id="server_upload" action="{% url 'server:domain_upload' %}" method="post" enctype="multipart/form-data">
                                    <div id="tips"></div>

                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="exampleInputFile" class="col-sm-2 control-label">上传域名-IP数据</label>
                                        <div class="col-sm-10">
                                            <input type="file" id="id_upload_file" name="upload_file">
                                            <p class="help-block">请选择域名-IP数据文件(仅支持CSV格式)
                                                <a href="{% static 'templates/domain_template.csv' %}">点击下载域名-IP导入模板</a></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-offset-2">
                                        <input type="button" class="btn btn-primary" value="上传" id="upload_submit"/>
                                    </div>
                                    <div class="form-group col-sm-offset-2 " style="margin-top:20px;display:none;" id="not_add_list">
                                        <h4>报告：以下域名-IP映射未添加成功，域名或IP可能已经关联。</h4>
                                        <ul class="list-group">
                                          <li class="list-group-item">Cras justo odio</li>
                                          <li class="list-group-item">Dapibus ac facilisis in</li>
                                          <li class="list-group-item">Morbi leo risus</li>
                                          <li class="list-group-item">Porta ac consectetur ac</li>
                                          <li class="list-group-item">Vestibulum at eros</li>
                                        </ul>
                                    </div>
                                </form>


                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->

{% endblock %}
{% block script %}
    <script src="{% static "admin_lte/plugins/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "js/ajaxfileupload.js" %}"></script>
    <script src="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.min.js"%}"></script>
    <script>
    function upload_error(message){
        $("#tips").html('<div class="alert alert-danger"><strong>错误：</strong>' + message + '</div>');
    }
    function upload_success(message){
        $("#tips").html('<div class="alert alert-success"><strong>恭喜：</strong>' + message + '</div>');
    }
    function upload_process(){
        $("#tips").html('<div class="alert alert-info"><strong>请稍候：</strong>文件正在上传...</div>');
    }


    $(function(){
        $("#server_upload").delegate("input[type='file']", "change", function(){
            $("#tips").empty();
        });

        $("#upload_submit").click(function(){
            if(!$("#id_upload_file").val()){
                upload_error("请选择CSV文件上传！");
                return false;
            }
            upload_process();
            $.ajaxFileUpload ({
                url :'{% url 'server:domain_upload' %}',
                fileElementId :"id_upload_file",
                //secureuri,　　　　　　　 //是否启用安全提交，默认为false。
                dataType: "text",
                //服务器返回的数据类型。可以为xml,script,json,html。如果不填写，jQuery会自动判断。
                data:{"csrfmiddlewaretoken": $.cookie("csrftoken")},
                success :function(data){ //提交成功后自动执行的处理函数，参数data就是服务器返回的数据。
                    data = $.parseJSON($(data).text());
                    if(data.result == true){
                        upload_success(data.message);
                        if(data.not_add && data.not_add.length > 0){
                            var not_html = '';
                            $.each(data.not_add, function(i, v){
                                not_html += '<li class="list-group-item">'+v.ip + ' - '+ v.domain+'</li>';
                            });
                            $("#not_add_list").show().find('ul').html(not_html);
                        }
                    }else{
                        upload_error(data.message);
                    }
                }
            });
        });

    })
    </script>
{% endblock %}