api/urls.py
from django.conf.urls import url, include
import api.views as views


urlpatterns = [
    # url(r'^$', service_views.index, name='index'),
    url(r'^ip_hostname/(?P<ip>[\d\.]+)$', views.ip_to_hostname, name='ip_hostname'),
    url(r'^kpi_ding/$', views.kpi_ding, name='kpi_ding'),

]

ntdeploy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include('server.urls', namespace='server')),
    url(r'^options/', include('options.urls', namespace='options')),
    url(r'^grid/', include('grid.urls', namespace='grid')),
    url(r'^operating/', include('operating.urls', namespace='operating')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout),

    # url(r'^accounts/login/$', login, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
]

options/urls.py
from django.conf.urls import url, include
import options.views


urlpatterns = [
    url(r'^$', options.views.index, name='index'),
    url(r'^add_data', options.views.add_data, name='add_data'),
    url(r'^remove_data', options.views.remove_data, name='remove_data'),
    url(r'^page/', options.views.page, name='page'),
    url(r'^data_option/', options.views.data_option, name='data_option'),

]

options/models.py
# coding:utf-8

from common.models import BaseModel
from django.db import models


class DataOption(BaseModel):
    category = models.CharField('分类', max_length=12, null=True, blank=True)
    keyword = models.CharField('关键字', max_length=20, null=True, blank=True)
    service_type = models.CharField('服务类型（服务类别专属）', max_length=50, default='')
    remark = models.CharField('备注', max_length=40, null=True, blank=True)

    def insert(self):
        if self.category and self.keyword:
            if DataOption.objects.filter(category=self.category, keyword__iexact=self.keyword).count() == 0:
                self.save()
                return True
        return False

    class Meta:
        verbose_name = '数据字典'
        permissions = (("view_dataoption", "访问数据字典"),)

options/forms.py
#!/usr/bin/python
# coding:utf-8
from django import forms


class DataOptionForm(forms.Form):
    id = forms.IntegerField(required=False)
    keyword = forms.CharField(max_length=20, required=True)
    service_type = forms.CharField(max_length=50, required=False)
    category = forms.CharField(max_length=12, required=True)
    remark = forms.CharField(max_length=40, required=False)


def main():
    pass


if __name__ == "__main__":
    main()

options/views.py
# coding:utf-8
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from options.models import DataOption
import logging
from common.forms import PageData
import traceback
from options.forms import DataOptionForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from common.permissions import *


log = logging.getLogger('django')


@login_required
@permission_required(VIEW_DATAOPTION)
def index(request):
    return render(request, 'options/index.html', locals())


@login_required
@permission_required(VIEW_DATAOPTION, raise_exception=True)
def page(request):
    log.info('searching option data...')
    dp = PageData(request.GET)
    category = request.GET.get('category', '')
    if dp.is_valid():
        page_info = dp.get_page_info()

        try:
            query = DataOption.objects.all()
            if category:
                query = query.filter(category=category)
            order = dp.get_sort_rule()
            order_col = order[0]
            if order[1] != 'asc':
                order_col = "-" + order[0]
            data = query.order_by(order_col)[page_info[0]:page_info[0]+page_info[1]]
            data = [x.to_dict() for x in data]
            length = query.count()
            mp = dp.get_data(data, length)
            log.info("search option data success. find: %s" % length)
            return JsonResponse(mp)
        except Exception:
            log.error('search get the ERROR: ' + traceback.format_exc())
            return JsonResponse({'result': False, 'message': 'search get the ERROR: \n'})
    return JsonResponse({'result': False, 'message': 'the Request params probably lose something.'})


@login_required
@permission_required(perm=(VIEW_DATAOPTION, ADD_DATAOPTION, CHANGE_DATAOPTION), raise_exception=True)
def add_data(request):
    if request.method == "POST":
        do = DataOptionForm(request.POST)
        if do.is_valid():
            data = do.cleaned_data
            if data['id']:
                # update
                DataOption.objects.filter(id=data['id']).update(
                    category=data['category'],
                    keyword=data['keyword'],
                    service_type=data['service_type'],
                    remark=data['remark']
                )
                log.info("Data Option update Sucess.")
                return JsonResponse({'result': True, 'message': '修改成功！'})
            else:
                # insert
                # 去除重复的keyword
                if DataOption.objects.filter(keyword__iexact=data['keyword'],
                                             category__iexact=data['category']).count() > 0:
                    return JsonResponse({'result': False, 'message': '已存在相同的数据！'})
                DataOption(
                    category=data['category'],
                    keyword=data['keyword'],
                    service_type=data['service_type'],
                    remark=data['remark']
                ).save()
                log.info("Data Option saved Sucess.")
                return JsonResponse({'result': True, 'message': '添加成功！'})
        else:
            log.error("Data Option submitted has missed params")
            return JsonResponse({'result': False, 'message': '请填写名称'})
    else:
        pass


@login_required
@permission_required(perm=(DELETE_DATAOPTION,), raise_exception=True)
def remove_data(request):
    do_id = request.POST.getlist("id[]", [])
    log.info("start Remove Server: " + str(do_id))
    if not do_id:
        log.error("Remove Server not appoint!")
        return JsonResponse({'result': False, 'message': '请输入要删除的Server ID'})

    try:
        DataOption.objects.filter(id__in=do_id).delete()
        log.info('Data option delete Sucess！' + str(do_id))
        return JsonResponse({'result': True, 'message': ''})
    except Exception as e:
        log.error("Data option Remove Failed! Caused by: \n" + traceback.format_exc())
        return JsonResponse({'result': False, 'message': '删除失败：' + e.message})


@login_required
@permission_required(VIEW_DATAOPTION)
def data_option(request):
    return render(request, 'options/data_option.html', locals())

templates/options/data_option.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load data_option_tags %}
{% block css %}
    <link rel="stylesheet" href="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.css" %}">
    <style type="text/css">
    table.dataTable tbody tr.selected {
        background-color: #B0BED9;
    }
    table.dataTable.row-border tbody th, table.dataTable.row-border tbody td, table.dataTable.display tbody th, table.dataTable.display tbody td {
        border-top: 1px solid #ddd;
        line-height: 35px;
    }
    </style>
{% endblock %}

{% block body %}


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    数据字典设置
                    <small>设置各页面下拉项：机房/标签等</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li class="active">数据字典设置</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <form class="form-inline" action="javascript:void(0);" id="search_form" role="form" style="margin-bottom: 20px;">

                                  <div class="form-group">
                                    <label class="sr-only" for="area_select">机房</label>

                                    <select id="area_select" name="category" class="form-control">
                                      <option value="">分类-全部</option>
                                      {% data_option '_category' %}
                                    </select>
                                  </div>
                                  <button type="submit" id="search_submit" class="btn btn-default">搜索</button>
                                </form>
                                <button type="button" class="btn btn-primary" id="add_model_show">添加</button>
                                <button type="button" class="btn btn-primary" id="batch_delete">删除</button>

                            </div><!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <table id="example" class="display table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>操作</th>
                                        <th>名称</th>
                                        <th>服务类别</th>
                                        <th>分类</th>
                                        <th>备注</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">添加/修改服务类别</h4>
      </div>
      <div class="modal-body">
          <div id="tips"></div>

          <form action="javascript:void(0);" id="save_form" class="form-horizontal" role="form" method="post">
              <input type="hidden" name="id">
              <div class="form-group">
                <label for="id_keyword" class="col-sm-2 control-label">名称</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control fa fa-dashboard" id="id_keyword" name="keyword" placeholder="请输入名称">
                </div>
              </div>

              <div class="form-group">
                <label for="id_category" class="col-sm-2 control-label">分类</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control fa fa-dashboard" id="id_category" name="category" placeholder="请输入数据字典类别">
                </div>
              </div>
              <div class="form-group" id="div_service_type">
                <label for="id_service_type" class="col-sm-2 control-label">依赖</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control fa fa-dashboard" id="id_service_type" name="service_type" placeholder="请输入服务的依赖：java/php等等（仅用于service）">
                </div>
              </div>
              <div class="form-group">
                <label for="id_remark" class="col-sm-2 control-label">备注</label>
                <div class="col-sm-10">
                  <textarea id="id_remark" class="form-control" rows="3" name="remark">{{ srv.remark }}</textarea>
                </div>
              </div>
             {% comment %} <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="button" id="submit_btn" class="btn btn-primary">保存并部署</button>
                </div>
              </div>{% endcomment %}
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save_submit">保存修改</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}
{% block script %}
    <script src="{% static "admin_lte/plugins/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.min.js"%}"></script>
    <script>
    function upload_error(message){
        $("#tips").html('<div class="alert alert-danger"><strong>错误：</strong>' + message + '</div>');
    }
    function upload_success(message){
        $("#tips").html('<div class="alert alert-success"><strong>恭喜：</strong>' + message + '</div>');
    }
    function upload_process(){
        $("#tips").html('<div class="alert alert-info"><strong>请稍候：</strong>文件正在上传...</div>');
    }
        $(function(){
            var $table = $("#example");
            var table = $table.DataTable({
                "bFilter": false,//去掉搜索框
                //"bAutoWidth": true, //自适应宽度
                "sPaginationType" : "full_numbers",
                //"sAjaxDataProp" : "aData",
                "bDestroy" : true,
                "bProcessing" : true,
                "iDisplayLength": 25,
                "sAjaxSource" : "{% url 'options:page' %}?category=",
                "bServerSide" : true,
                "columns" : [
                    { 'data': null},
                    { 'data': 'id'},
                    { 'data': 'keyword'},
                    { 'data': 'service_type'},
                    { 'data': 'category'},
                    { 'data': 'remark'}
                ],
                "columnDefs": [
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets":0
                         // "visible": false,
                    },
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets":3,
                        "visible": false
                    },
                    {
                        "targets": 1,//操作
                        "render": function(data, type, row, meta) {
                            return "<button class='btn btn-default server-update' type='button' data-id='"+data+"' data-service-type='"+row.service_type+"'><i class='fa fa-edit'></i></button>" +
                                    "&nbsp;&nbsp;<button class='btn btn-default server-delete' type='button' data-id='"+data+"'><i class='fa fa-trash-o'></i></button>"
                        }
                    }
                ],
                "order": [[ 2, 'asc' ]],

                "oLanguage" : {
                    "sProcessing" : "正在加载中......",
                    "sLengthMenu" : "每页显示 _MENU_ 条记录",
                    "sZeroRecords" : "没有数据！",
                    "sEmptyTable" : "表中无数据存在！",
                    "sInfo" : "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
                    "sInfoEmpty" : "显示0到0条记录",
                    "sInfoFiltered" : "数据表中共为 _MAX_ 条记录",
                    //"sSearch" : "搜索",
                    "oPaginate" : {
                        "sFirst" : "首页",
                        "sPrevious" : "上一页",
                        "sNext" : "下一页",
                        "sLast" : "末页"
                    }
                }
            });
            // 选中操作
            table.on( 'click', 'tr[role="row"]', function () {
                $(this).toggleClass('selected');
            } );
            // 添加序号
            table.on( 'order.dt search.dt', function () {
                table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                    cell.innerHTML = i+1;
                } );
            } ).draw();

            $("#add_model_show").click(function(){
                $("#save_form")[0].reset();
                $("#save_form").find("input[name='id']").val('');
                $("#div_service_type").hide();
                $('#myModal').modal('show');
            });

            $("input[name='category']").change(function(){
                if($(this).val() == 'service'){
                    $("#div_service_type").show();
                }else{
                    $("#div_service_type").hide();
                }
            });

            $("#save_submit").click(function(){
{#                $("#save_form")[0].reset();#}
                var keyword = $("#id_keyword").val();
                if(keyword == ''){
                    upload_error("请填写名称！");
                    return false;
                }
                simple_ajax({
                    url: "{% url 'options:add_data' %}",
                    data: $("#save_form").serialize(),
                    success: function(data){
                        if(data.result == true){
                            $('#myModal').modal('hide');
                            table.ajax.reload();
                        }else{
                            upload_error(data.message);
                        }
                    }
                })
            });


            function batch_delete(server_ids){
                simple_ajax({
                    url: "{% url 'options:remove_data' %}",
                    data:{"id": server_ids},
                    success:function(data){
                        if(data.result == true){
                            table.ajax.reload()
                        }else{
                            alert("删除失败！" + data.message)
                        }
                    }
                })
            }

            $("#batch_delete").click(function(){
                // console.log(table.rows('.selected').data())
                var datas = table.rows('.selected').data();
                var length = datas.length;
                if(length > 0){
                    if(confirm("您确定要删除这" + length + "个Service吗？")){
                        var server_ids = [];
                        for(i=0; i<length; i++){
                            server_ids.push(datas[i].id);
                        }
                        batch_delete(server_ids)
                    }
                }else{
                    alert('请至少选择一个Service');
                }
            });
            $table.delegate('.server-delete', 'click', function(){
                if(confirm("您确定要删除该Server吗？")){
                    batch_delete([$(this).attr("data-id")]);
                }
            });
            $table.delegate('.server-update', 'click', function(){
                var $current = $(this);
                var id = $current.attr("data-id");
                var $tr = $current.parents("tr");
                var keyword = $tr.find("td:eq(2)").text();
                var category = $tr.find("td:eq(3)").text();
                var service_type = $current.attr("data-service-type");
                var remark = $tr.find("td:eq(4)").text();
                $("input[name='id']").val(id);
                $("input[name='category']").val(category);
                $("input[name='keyword']").val(keyword);
                $("input[name='service_type']").val(service_type);
                $("textarea[name='remark']").val(remark);
                if(category != 'service'){
                    $("#div_service_type").hide();
                }else{
                    $("#div_service_type").show();
                }
                $('#myModal').modal('show');
            });
            $("#search_form").submit(function(){
                var search_query = $(this).serialize();
                table.ajax.url("{% url 'options:page' %}?" + search_query).load();
                return false;
            });
        })
    </script>
{% endblock %}