api/urls.py
from django.conf.urls import url, include
import api.views as views


urlpatterns = [
    # url(r'^$', service_views.index, name='index'),
    url(r'^ip_hostname/(?P<ip>[\d\.]+)$', views.ip_to_hostname, name='ip_hostname'),
    url(r'^kpi_ding/$', views.kpi_ding, name='kpi_ding'),

]

ntdeploy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include('server.urls', namespace='server')),
    url(r'^options/', include('options.urls', namespace='options')),
    url(r'^grid/', include('grid.urls', namespace='grid')),
    url(r'^operating/', include('operating.urls', namespace='operating')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout),

    # url(r'^accounts/login/$', login, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
]

server/urls.py
# coding=utf-8
from django.conf.urls import url, include
import server.views as server_views
import server.views_domain as domain_views
import cmdb.views as cmdb_views

urlpatterns = [
    # url(r'^$', server_views.index, name='index'),
    url(r'^page/', server_views.page, name='page'),
    url(r'^page_enabled/', server_views.page_enabled, name='page_enabled'),
    url(r'^upload/', server_views.upload, name='upload'),
    url(r'^add/', server_views.add, name='add'),
    url(r'^update/(?P<srv_id>\d+)/', server_views.update, name='update'),
    # url(r'^remove/', server_views.remove_server, name='remove'),
    url(r'^search_by_area/', server_views.search_by_area, name='search_by_area'),
    url(r'^view_log/(?P<srv_id>\d+)/', server_views.view_log, name='view_log'),
    url(r'^connect/(?P<srv_id>\d+)/', server_views.connect, name='connect'),

    # domain urls
    url(r'^domain/$', domain_views.index, name='domain_index'),
    url(r'^domain/page/', domain_views.page, name='domain_page'),
    url(r'^domain/add/', domain_views.add, name='domain_add'),
    url(r'^domain/update/(?P<dmn_id>\d+)/', domain_views.update, name='domain_update'),
    url(r'^domain/remove/', domain_views.remove, name='domain_remove'),
    url(r'^domain/upload/', domain_views.upload, name='domain_upload'),

    # cmdb
    url(r'^$', cmdb_views.service_info, name='index'),
    url(r'^index_phone', cmdb_views.service_info_phone, name='index_phone'),
    url(r'^update_info/', cmdb_views.update_info, name='update_info'),
    url(r'^job_list_page/', cmdb_views.job_list_page, name='job_list_page'),
    url(r'^job_list_page_phone/', cmdb_views.job_list_page_phone, name='job_list_page_phone'),
    url(r'^eip_page/', cmdb_views.eip_page, name='eip_page'),
    url(r'^export/', cmdb_views.export, name='export'),
    url(r'^show_del_server/', cmdb_views.show_del_server, name='show_del_server'),
    url(r'^del_list_page/', cmdb_views.del_list_page, name='del_list_page'),
    url(r'^update_status_page/', cmdb_views.update_status_page, name='update_status_page'),
    url(r'^show_update_info/', cmdb_views.show_update_info, name='show_update_info'),
    url(r'^do_operate/', cmdb_views.do_operate, name='do_operate'),
    url(r'^add_server/', cmdb_views.add_server, name='add_server'),
    url(r'^check_ssh_copy/', cmdb_views.check_ssh_copy, name='check_ssh_copy'),
    url(r'^services/', cmdb_views.restart_service, name='restart_service'),

    url(r'^modify/(?P<srv_id>\d+)/', cmdb_views.modify, name='modify'),
    url(r'^deeply_delete/', cmdb_views.deeply_delete, name='deeply_delete'),

    url(r'^group/', cmdb_views.group_index, name='group'),
    url(r'^eip/', cmdb_views.eip_index, name='eip'),
    url(r'^group_page/', cmdb_views.group_page, name='group_page'),
    url(r'^add_group/', cmdb_views.add_group, name='add_group'),
    url(r'^get_servers/', cmdb_views.get_servers, name='get_servers'),
    url(r'^update_group/(?P<gid>\d+)/', cmdb_views.update_group, name='update_group'),
    url(r'^remove_group/', cmdb_views.remove_group, name='remove_group'),

    # api
    url(r'^add_server_api/', cmdb_views.add_server_api, name='add_server_api'),
    url(r'^route_shell/', cmdb_views.route_shell, name='route_shell'),

]

cmdb/models.py
# coding: utf-8

from django.db import models
from common.models import BaseManager, BaseModel
from django.db.models import Q
from common.util.des import encrypt


class ServerGroup(BaseModel):
    name = models.CharField('主机组名', max_length=40, null=False)
    count = models.IntegerField('主机数量', default=0)
    remark = models.CharField('备注', max_length=100, null=True, blank=True)
    label = models.IntegerField('分类0自动生成, 1手动添加', default=0)

    def __unicode__(self):
        return "ServerGroup<%s>" % self.name

    class Meta:
        verbose_name = '资产组管理'


class ServerInfo(BaseModel):
    RegionId = models.CharField('地域', max_length=40, null=False)
    ZoneId = models.CharField('可用区', max_length=40, null=True, default='')
    InstanceId = models.CharField('实例的编号', max_length=40, null=False, unique=True)
    InstanceName = models.CharField('实例名称', max_length=40, null=False)
    InstanceType = models.CharField('类型', max_length=40, null=True, blank=True)    # ecs
    PublicIpAddress = models.CharField('公网IP', max_length=80, null=False)
    InnerIpAddress = models.CharField('内网IP', max_length=80, null=False)
    IpType = models.CharField('IP地址网络类型', max_length=12, default='default')
    # aliyun :Running Starting Stopping Stopped
    # ksyun: 有效值: active | building | paused | suspended | stopped | rescued | resized | soft-delete | deleted | deleting | error | scheduling |
        # block_device_mapping | networking | spawning | image_snapshot | image_backup | updating_password | resize_prep | resize_migrating |
        # resize_migrated | resize_finish | resize_finish | resize_reverting | resize_confirming | migrating | rebooting | rebooting_hard | pausing |
        # unpausing | suspending | resuming | stopping | starting | powering-off | powering-on | rescuing | unrescuing | rebuilding |
        # rebuild_block_device_mapping | rebuild_spawning | deleting
    Status = models.CharField('状态', max_length=40, null=False)
    Cpu = models.IntegerField('CPU数量', default=0)
    Cpu_info = models.CharField('CPU信息', max_length=50, blank=True, null=True)
    Memory = models.IntegerField('内存大小GB', default=0)
    DiskSize = models.IntegerField('硬盘大小GB', default=0)
    DiskType = models.CharField('硬盘类型 SATA | SSD | EFFICIENCY(混合)', max_length=50, blank=True, default="SATA", null=True)
    InternetMaxBandwidthOut = models.IntegerField('带宽', default=0)
    InternetMaxBandwidthIn = models.IntegerField('带宽下载', default=0)
    ansible_host = models.CharField('可连接到主机的IP，供ansible使用', max_length=100, null=True, blank=True)
    os = models.CharField('操作系统', max_length=50, blank=True, null=True)
    os_release = models.CharField('操作系统发行版本', max_length=50, blank=True, null=True)
    os_version = models.CharField('操作系统版本', max_length=50, blank=True, null=True)
    enabled = models.IntegerField('状态值，是否可用。默认为可用', default=0)
    """
    0:可用
    1:不可用
    """
    group = models.ManyToManyField(ServerGroup, db_constraint=False)
    sys_bits = models.CharField('操作系统位数', max_length=20, blank=True, null=True)

    # hand input info in form
    server_location = models.CharField('服务器存放地点', max_length=50, blank=True, null=True)
    sn = models.CharField('服务器sn号', max_length=50, blank=True, null=True)
    user = models.CharField('用户', max_length=50, blank=True, null=True)
    pwd = models.CharField('密码', max_length=50, blank=True, null=True)
    port = models.IntegerField('端口号', blank=False, default=22)
    remark = models.CharField('备注', max_length=200, blank=True, null=True)
    connect_log = models.TextField('连接日志', null=True)
    connect = models.IntegerField('连接状态【0未连接，1正在连接，2已连接，-1连接失败】', default=0)

    def to_dict(self):
        server_dict = super(self.__class__, self).to_dict()
        server_dict['groups'] = [g.to_dict() for g in self.group.all()]
        return server_dict

    def insert(self, enc=False):
        if not self.port:
            self.port = 8022
        self.port = int(self.port)
        if self.InnerIpAddress and self.PublicIpAddress:
            q_filter = Q(InnerIpAddress__contains=self.InnerIpAddress) | Q(PublicIpAddress__contains=self.PublicIpAddress)
        elif self.PublicIpAddress:
            q_filter = Q(PublicIpAddress__contains=self.PublicIpAddress)
        elif self.InnerIpAddress:
            q_filter = Q(InnerIpAddress__contains=self.InnerIpAddress)
        if enc:
            self.pwd = encrypt(self.pwd) if self.pwd else ""
        if ServerInfo.objects.filter(q_filter).count() == 0:
            self.save()
            return True
        return False

    def __unicode__(self):
        return "ServerInfo<%d, %s>" % (self.id, self.InstanceName)

    class Meta:
        verbose_name = 'CMDB-Server管理'


class KsyEipManager(BaseManager):
    def insert(self, data_dict):
        # data_dict = {
        #     "PublicIp": "120.92.77.179",
        #     "AllocationId": "fe3d61af-7964-4ed0-a061-06aea4b8ecd0",
        #     "State": "disassociate",
        #     "LineId": "5fc2595f-1bfd-481b-bf64-2d08f116d800",
        #     "BandWidth": 5,
        #     "CreateTime": "2017-01-05 15:27:22"
        # }
        for key in ['NetworkInterfaceId', 'InstanceType', 'InstanceId', 'InternetGatewayId']:
            if key not in data_dict:
                data_dict[key] = ''
        eips = self.filter(AllocationId=data_dict['AllocationId'])
        if not eips:
            eip = KsyEip()
        else:
            eip = eips[0]
        eip.AllocationId = data_dict['AllocationId']
        eip.PublicIp = data_dict['PublicIp']
        eip.State = data_dict['State']
        eip.LineId = data_dict['LineId']
        eip.BandWidth = data_dict['BandWidth']
        eip.CreateTime = data_dict['CreateTime']
        # 金山云API可选项
        eip.NetworkInterfaceId = data_dict['NetworkInterfaceId']
        eip.InstanceType = data_dict['InstanceType']
        eip.InstanceId = ServerInfo.objects.safe_get(InstanceId=data_dict['InstanceId'])
        eip.InternetGatewayId = data_dict['InternetGatewayId']
        eip.save()



class KsyEip(BaseModel):
    '''
    CREATE TABLE `ntdeploy`.`cmdb_ksyeip` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `PublicIp` VARCHAR(16) NOT NULL,
      `AllocationId` VARCHAR(40) NOT NULL,
      `State` VARCHAR(16) NOT NULL,
      `LineId` VARCHAR(40) NOT NULL,
      `NetworkInterfaceId` VARCHAR(40) NULL,
      `BandWidth` INT NULL DEFAULT 0,
      `InstanceType` VARCHAR(40) NULL,
      `InstanceId` VARCHAR(40) NULL,
      `InternetGatewayId` VARCHAR(40) NULL,
      `CreateTime` VARCHAR(40) NULL,
      `create_time` DATETIME NOT NULL,
      `update_time` DATETIME NOT NULL
      PRIMARY KEY (`id`));
    '''
    PublicIp = models.CharField('弹性IP地址', max_length=16, null=False, blank=False)
    AllocationId = models.CharField('分配ID', max_length=40, null=False, blank=False)
    State = models.CharField('EIP状态(associate/disassociate)', max_length=40, null=False, blank=False)
    LineId = models.CharField('链路ID', max_length=40, null=False, blank=False)
    NetworkInterfaceId = models.CharField('网卡ID', max_length=40, null=False, blank=True, default='')
    BandWidth = models.IntegerField('带宽', null=False, default=0)
    InstanceType = models.CharField('EIP类型(Ipfwd/Slb)', max_length=40, null=False, default=0)
    # InstanceId = models.CharField('EIP实例ID', max_length=40, null=False, blank=True, default='')
    InstanceId = models.OneToOneField(ServerInfo, to_field='InstanceId', db_constraint=False)
    InternetGatewayId = models.CharField('网关ID', max_length=40, null=False, blank=True, default='')
    CreateTime = models.CharField('创建时间', max_length=40, null=False, blank=True, default='')

    objects = KsyEipManager()

cmdb/forms.py
#!/usr/bin/python
# coding:utf-8
__author__ = 'Fengxu'
from django import forms


class FileForm(forms.Form):
    upload_file = forms.FileField()


class AddServer(forms.Form):
    id = forms.IntegerField(required=False)
    # name = forms.CharField(max_length=20)
    inner_ip = forms.CharField(required=False, max_length=16)
    outer_ip = forms.CharField(required=False, max_length=16)
    area = forms.CharField(max_length=40)
    user = forms.CharField(max_length=20)
    password = forms.CharField(max_length=40)
    port = forms.IntegerField(required=False)
    sn = forms.CharField(required=False)
    remark = forms.CharField(required=False)


class AddDomain(forms.Form):
    id = forms.IntegerField(required=False)
    type = forms.CharField()
    domain = forms.CharField(max_length=80)
    ip = forms.CharField(max_length=16)
    category = forms.IntegerField()
    remark = forms.CharField(max_length=40, required=False)


class AddServerApiForm(forms.Form):
    innerIp = forms.CharField(max_length=40, required=False)
    publicIp = forms.CharField(max_length=40, required=False)
    user = forms.CharField(max_length=40, required=False)
    port = forms.IntegerField(required=False)
    kw = forms.CharField(required=False)


def main():
    pass


if __name__ == "__main__":
    main()

templates/cmdb/add_server.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}配置管理系统_V1.0.0{% endblock %}
{% block css %}

{% endblock %}

{% block body %}


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {% if srv %}修改{% else %}添加{% endif %}Server
                {#                    <small>控制面板</small>#}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a href="{% url 'server:index' %}"><i class="fa fa-server"></i> Server列表</a></li>
                <li class="active">{% if srv %}修改Server{% else %}添加Server{% endif %}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            {% if message and message.result == False %}
                                <div class="alert alert-danger"><strong>添加失败：</strong>{{ message.message }}</div>
                            {% endif %}

                            <form id="server_form" class="form-horizontal" role="form" action="
                                    {% if srv %}{% url 'server:modify' srv_id=srv.id %}{% else %}{% url 'server:add_server' %}{% endif %}"
                                  method="post" onsubmit="return validate()">
                                <input id="id_id" name="id" type="hidden" value="{{ srv.id }}"/>
                                <input name="server_id" type="hidden" value="{{ srv.server_id }}"/>
                                <input name="type" type="hidden" value="{% if srv %}update{% else %}add{% endif %}"/>
                                {% csrf_token %}
{#                                <div class="form-group">#}
{#                                    <label for="id_name" class="col-sm-2 control-label">主机名</label>#}
{##}
{#                                    <div class="col-sm-10">#}
{#                                        <input type="text" class="form-control" id="id_name" name="name"#}
{#                                               placeholder="主机名" required value="{{ srv.InstanceName }}">#}
{#                                    </div>#}
{#                                </div>#}
                                <div class="form-group">
                                    <label for="id_inner_ip" class="col-sm-2 control-label">内网IP</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_inner_ip" name="inner_ip"
                                               placeholder="内网IP" value="{{ srv.InnerIpAddress }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_outer_ip" class="col-sm-2 control-label">外网IP</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_outer_ip" name="outer_ip"
                                               placeholder="外网IP" value="{{ srv.PublicIpAddress }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_area" class="col-sm-2 control-label">来源</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_area" name="area"
                                               placeholder="来源" required value="{{ srv.RegionId }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_user" class="col-sm-2 control-label">用户名</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_user" name="user"
                                               placeholder="用户名" value="{{ srv.user }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_password" class="col-sm-2 control-label">密码</label>

                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="id_password" name="password"
                                               placeholder="密码（不填写表示已经连接）" value="{{ srv.pwd }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_port" class="col-sm-2 control-label">端口</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_port" name="port"
                                               placeholder="端口" value="{% if srv %}{{ srv.port }}{% else %}8022{% endif %}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_sn" class="col-sm-2 control-label">SN号</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_sn" name="sn" placeholder="SN号"
                                               value="{{ srv.sn }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_remark" class="col-sm-2 control-label">备注</label>

                                    <div class="col-sm-10">
                                        <textarea id="id_remark" class="form-control" rows="4" name="remark"
                                                  value="{{ srv.remark }}">{{ srv.remark }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="button" class="btn btn-primary" id="submit_btn">{% if srv %}修改{% else %}
                                            添加{% endif %}Server
                                        </button>
                                    <br>
                                    <br>
                                    <div style="display: none" class="alert alert-warning" id="check_alert">稍后，请等待验证。。。{{ message.message }}</div>

                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div><!-- /.content-wrapper -->
{% endblock %}
{% block script %}
    <script>
        function validate() {
            var $inner_ip = $("input[name='inner_ip']");
            var $outer_ip = $("input[name='outer_ip']");
            if ($inner_ip.val() == "" && $outer_ip.val() == "") {
                alert("内网IP和外网IP必须填写一项！");
                return false;
            }
        }


    //提交按钮,在提交的同时，包含拷贝秘钥验证功能（如果server连接成功，则可以正常添加到数据库，反之亦然）
        $("#submit_btn").click(function () {
            var srv_inner_ip = $('#id_inner_ip').val()
            var srv_outer_ip = $('#id_outer_ip').val()
            var srv_user = $('#id_user').val()
            var srv_pwd = $('#id_password').val()
            var srv_port = $('#id_port').val()
            $('#check_alert').show()
            simple_ajax({
                url: '{% url 'server:check_ssh_copy' %}',
                data: {
                    srv_inner_ip: srv_inner_ip,
                    srv_outer_ip: srv_outer_ip,
                    srv_user: srv_user,
                    srv_pwd: srv_pwd,
                    srv_port: srv_port
                },
                success: function (data) {
                    if (data.result == false) {
                        alert(data.message + "请检查ip和用户名密码、端口是否填写正确!");
                    }
                    else{
                        $("#server_form").submit();
                    }
                }
            });
        });


    </script>
{% endblock %}

templates/cmdb/add_server_result.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {{ message.title }}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:index' %}"><i class="fa fa-server"></i> Server列表</a></li>
                    <li><a href="{% url 'server:add' %}"><i class="fa fa-server"></i> 添加Server</a></li>
                    <li class="active">{{ message.title }}</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">{{ message.message }}</h3>

                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <a href="{% url 'server:index' %}">点击转到Server列表</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}