api/urls.py
from django.conf.urls import url, include
import api.views as views


urlpatterns = [
    # url(r'^$', service_views.index, name='index'),
    url(r'^ip_hostname/(?P<ip>[\d\.]+)$', views.ip_to_hostname, name='ip_hostname'),
    url(r'^kpi_ding/$', views.kpi_ding, name='kpi_ding'),

]

ntdeploy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include('server.urls', namespace='server')),
    url(r'^options/', include('options.urls', namespace='options')),
    url(r'^grid/', include('grid.urls', namespace='grid')),
    url(r'^operating/', include('operating.urls', namespace='operating')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^accounts/login/$', views.login),
    url(r'^accounts/logout/$', views.logout),

    # url(r'^accounts/login/$', login, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
]

server/urls.py
# coding=utf-8
from django.conf.urls import url, include
import server.views as server_views
import server.views_domain as domain_views
import cmdb.views as cmdb_views

urlpatterns = [
    # url(r'^$', server_views.index, name='index'),
    url(r'^page/', server_views.page, name='page'),
    url(r'^page_enabled/', server_views.page_enabled, name='page_enabled'),
    url(r'^upload/', server_views.upload, name='upload'),
    url(r'^add/', server_views.add, name='add'),
    url(r'^update/(?P<srv_id>\d+)/', server_views.update, name='update'),
    # url(r'^remove/', server_views.remove_server, name='remove'),
    url(r'^search_by_area/', server_views.search_by_area, name='search_by_area'),
    url(r'^view_log/(?P<srv_id>\d+)/', server_views.view_log, name='view_log'),
    url(r'^connect/(?P<srv_id>\d+)/', server_views.connect, name='connect'),

    # domain urls
    url(r'^domain/$', domain_views.index, name='domain_index'),
    url(r'^domain/page/', domain_views.page, name='domain_page'),
    url(r'^domain/add/', domain_views.add, name='domain_add'),
    url(r'^domain/update/(?P<dmn_id>\d+)/', domain_views.update, name='domain_update'),
    url(r'^domain/remove/', domain_views.remove, name='domain_remove'),
    url(r'^domain/upload/', domain_views.upload, name='domain_upload'),

    # cmdb
    url(r'^$', cmdb_views.service_info, name='index'),
    url(r'^index_phone', cmdb_views.service_info_phone, name='index_phone'),
    url(r'^update_info/', cmdb_views.update_info, name='update_info'),
    url(r'^job_list_page/', cmdb_views.job_list_page, name='job_list_page'),
    url(r'^job_list_page_phone/', cmdb_views.job_list_page_phone, name='job_list_page_phone'),
    url(r'^eip_page/', cmdb_views.eip_page, name='eip_page'),
    url(r'^export/', cmdb_views.export, name='export'),
    url(r'^show_del_server/', cmdb_views.show_del_server, name='show_del_server'),
    url(r'^del_list_page/', cmdb_views.del_list_page, name='del_list_page'),
    url(r'^update_status_page/', cmdb_views.update_status_page, name='update_status_page'),
    url(r'^show_update_info/', cmdb_views.show_update_info, name='show_update_info'),
    url(r'^do_operate/', cmdb_views.do_operate, name='do_operate'),
    url(r'^add_server/', cmdb_views.add_server, name='add_server'),
    url(r'^check_ssh_copy/', cmdb_views.check_ssh_copy, name='check_ssh_copy'),
    url(r'^services/', cmdb_views.restart_service, name='restart_service'),

    url(r'^modify/(?P<srv_id>\d+)/', cmdb_views.modify, name='modify'),
    url(r'^deeply_delete/', cmdb_views.deeply_delete, name='deeply_delete'),

    url(r'^group/', cmdb_views.group_index, name='group'),
    url(r'^eip/', cmdb_views.eip_index, name='eip'),
    url(r'^group_page/', cmdb_views.group_page, name='group_page'),
    url(r'^add_group/', cmdb_views.add_group, name='add_group'),
    url(r'^get_servers/', cmdb_views.get_servers, name='get_servers'),
    url(r'^update_group/(?P<gid>\d+)/', cmdb_views.update_group, name='update_group'),
    url(r'^remove_group/', cmdb_views.remove_group, name='remove_group'),

    # api
    url(r'^add_server_api/', cmdb_views.add_server_api, name='add_server_api'),
    url(r'^route_shell/', cmdb_views.route_shell, name='route_shell'),

]

server/models.py
# coding: utf-8


from django.db import models
from common.models import BaseModel, BaseManager
import datetime
import time
from common.util.mysql_util import connect
import logging
from common.util import des
from common.util import id_creater
import traceback
from common.util.des import encrypt
from django.db.models import Q
from common.util.id_creater import server_id


log = logging.getLogger('django')


class Server(BaseModel):
    """Server Manage Table"""
    server_id = models.CharField('ServerID', max_length=20, unique=True, null=True)
    category = models.CharField('Server类别', max_length=12, blank=True, null=True)
    name = models.CharField('名称', max_length=48, blank=True, null=True)
    hostname = models.CharField('主机名', max_length=20, blank=True, null=True)
    inner_ip = models.CharField('内网IP', max_length=16, blank=True, null=True)
    outer_ip = models.CharField('公网IP', max_length=16, blank=True, null=True)
    user = models.CharField('用户', max_length=20, blank=True, null=True)
    password = models.CharField('密码', max_length=100, blank=True, null=True)
    port = models.IntegerField('端口', default=22, blank=False)
    os = models.CharField('操作系统', max_length=20, blank=True, null=True)
    memory = models.IntegerField('内存（单位MB）', default=0, null=True)
    memory_free = models.IntegerField('剩余内存（单位MB）', default=0, null=True)
    bandwidth = models.CharField('带宽', max_length=20, blank=True, null=True)
    cpu = models.CharField('CPU', max_length=200, blank=True, null=True)
    domain = models.CharField('域名', max_length=48, blank=True, null=True)
    rack = models.CharField('机架', max_length=40, blank=True, null=True)
    area = models.CharField('机房', max_length=20, blank=True, null=True)
    monitor = models.CharField('监控', max_length=100, blank=True, null=True)
    remark = models.CharField('备注', max_length=40, null=True, default="")
    connect = models.IntegerField('连接状态【0未连接，1正在连接，2已连接，-1连接失败】', default=0)
    connect_log = models.TextField('连接日志', null=True)
    ansible_host = models.CharField('可连接到主机的IP，供ansible使用', max_length=100, null=True, blank=True)
    state = models.IntegerField('服务器状态', default=0)

    def __unicode__(self):
        return "Server<%s>" % self.hostname

    def insert(self, enc=False):
        try:
            if not self.port:
                self.port = 22
            self.port = int(self.port)
            if not self.server_id:
                self.server_id = server_id()
        except ValueError:
            self.port = 22
        q_filter = Q(server_id=self.server_id)
        if self.inner_ip:
            q_filter |= Q(inner_ip=self.inner_ip)
        if self.outer_ip:
            q_filter |= Q(outer_ip=self.outer_ip)
        if enc:
            self.password = encrypt(self.password) if self.password else ""
        if Server.objects.filter(q_filter).count() == 0:
            self.save()
            return True
        return False

    class Meta:
        verbose_name = 'Server管理'
        permissions = (("view_server", "访问服务器"),)


class DomainManager(BaseManager):
    """
    Domain manager class
    """
    def page_search_data(self, page_start, page_size, orderby='domain', order_type='asc', kw="", area="", ip_category=2):
        """
        Domain get data by searching keyword and separate page info.
        :param page_start: separate page start record number
        :param page_size: the record number per page
        :param orderby: which column for order
        :param order_type: how to order (asc or desc)
        :param kw: search keyword for domain/ip/area/hostname and so oon
        :param area: search jifang info
        :param ip_category: the type of IP address
        :return: the tuple of searched data and total count: (data, length)
        """

        sql = " from server_domain d left join server_server s " \
              " on ( d.ip=s.inner_ip or d.ip=s.outer_ip ) where 1=1 "
        params = []
        if kw:
            sql += " and ( d.domain like %s or d.ip like %s " \
                   " or s.hostname like %s or s.area like %s ) "
            kw = "%" + kw + "%"
            params.extend([kw] * 4)
        if area:
            sql += " and s.area like %s "
            params.append("%" + area + "%")
        if ip_category != 2:
            sql += " and d.category=%s "
            params.append(str(ip_category))
        if orderby and order_type:
            sql += " order by %s %s "
            params.extend([orderby, order_type])
        length_sql = "select count(d.id) " + sql
        sql_data = "select d.* " + sql
        log.info("SQL for Count: " + length_sql % tuple(params))
        log.info("SQL for Data: " + sql_data % tuple(params))

        with connect() as cursor:
            cursor.execute(length_sql, params)
            count_row = cursor.fetchone()
            length = count_row[0]
        data = self.raw(sql_data, params)[page_start:page_start + page_size]
        log.info("searched Domain: " + str(data) + " size: " + str(length))
        return data, length

    def exists(self, category, ip, domain):
        """
        判断是否存在指定IP或指定域名的映射。
        :param category: IP类型 0内网，1外网
        :param ip: IP地址
        :param domain: 域名
        :return: 如果IP和域名存在其一，则返回True
        """
        if self.filter(category=category, ip=ip).count() > 0:
            return True
        if self.filter(domain=domain).count() > 0:
            return True
        return False


class Domain(BaseModel):
    domain = models.CharField('域名', max_length=80, blank=True, null=True)
    ip = models.CharField('IP地址', max_length=16, blank=True, null=True)
    category = models.IntegerField('IP类型【0内网IP，1外网IP】')
    remark = models.CharField('备注', max_length=40, null=False, default="")

    objects = DomainManager()

    def __unicode__(self):
        return "Domain<%s>" % self.domain

    def to_dict(self):
        if self.category == 0:
            servers = Server.objects.filter(inner_ip=self.ip)
        else:
            servers = Server.objects.filter(outer_ip=self.ip)
        if servers:
            server = servers[0].to_dict()
        else:
            server = None
        return dict(
            id=self.id,
            domain=self.domain,
            ip=self.ip,
            category=self.category,
            remark=self.remark,
            server=server
        )

    class Meta:
        verbose_name = '域名管理'
        permissions = (("view_domain", "访问域名映射"),)

server/forms.py
#!/usr/bin/python
# coding:utf-8
__author__ = 'Fengxu'
from django import forms


class FileForm(forms.Form):
    upload_file = forms.FileField()


class AddServer(forms.Form):
    id = forms.IntegerField(required=False)
    type = forms.CharField()
    name = forms.CharField(max_length=48)
    inner_ip = forms.CharField(required=False, max_length=16)
    outer_ip = forms.CharField(required=False, max_length=16)
    area = forms.CharField(max_length=20)
    user = forms.CharField(max_length=20, required=False)
    password = forms.CharField(max_length=40, required=False)
    port = forms.IntegerField(required=False)
    bandwidth = forms.CharField(max_length=40, required=False)
    monitor = forms.CharField(max_length=100, required=False)
    remark = forms.CharField(max_length=40, required=False)


class AddDomain(forms.Form):
    id = forms.IntegerField(required=False)
    type = forms.CharField()
    domain = forms.CharField(max_length=80)
    ip = forms.CharField(max_length=16)
    category = forms.IntegerField()
    remark = forms.CharField(max_length=40, required=False)


def main():
    pass


if __name__ == "__main__":
    main()

templates/server/add-result.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {{ message.title }}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:index' %}"><i class="fa fa-server"></i> Server列表</a></li>
                    <li><a href="{% url 'server:add' %}"><i class="fa fa-server"></i> 添加Server</a></li>
                    <li class="active">{{ message.title }}</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">{{ message.message }}</h3>

                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <a href="{% url 'server:index' %}">点击转到Server列表</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}

templates/server/add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}配置管理系统_V1.0.0{% endblock %}
{% block css %}

{% endblock %}

{% block body %}


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {% if srv %}更新{% else %}添加{% endif %}Server
{#                    <small>控制面板</small>#}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:index' %}"><i class="fa fa-server"></i> Server列表</a></li>
                    <li class="active">添加Server</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            {% comment %}<div class="box-header">
                                <h3 class="box-title">Server</h3>
                                <button type="button" id="button">点击获取</button>

                            </div>{% endcomment %}<!-- /.box-header -->
                            <div class="box-body">
                                {% if message and message.result == False %}
                                <div class="alert alert-danger"><strong>添加失败：</strong>{{ message.message }}</div>
                                {% endif %}
                                <form id="server_form" class="form-horizontal" role="form" action="{% if srv %}{% url 'server:update' srv_id=srv.id %}{% else %}{% url 'server:add' %}{% endif %}" method="post" onsubmit="return validate()">
                                    <input id="id_id" name="id" type="hidden" value="{{ srv.id }}"/>
                                    <input name="server_id" type="hidden" value="{{ srv.server_id }}"/>
                                    <input name="type" type="hidden" value="{% if srv %}update{% else %}add{% endif %}"/>
                                    {% csrf_token %}
                                  <div class="form-group">
                                    <label for="id_name" class="col-sm-2 control-label">主机名</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_name" name="name" placeholder="主机名" required value="{{ srv.name }}">
                                    </div>
                                  </div>
                                    <div class="form-group">
                                    <label for="id_inner_ip" class="col-sm-2 control-label">内网IP</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_inner_ip" name="inner_ip" placeholder="内网IP" value="{{ srv.inner_ip }}">
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <label for="id_outer_ip" class="col-sm-2 control-label">外网IP</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_outer_ip" name="outer_ip" placeholder="外网IP" value="{{ srv.outer_ip }}">
                                    </div>
                                  </div>
                                    <div class="form-group">
                                    <label for="id_area" class="col-sm-2 control-label">来源</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_area" name="area" placeholder="来源" required value="{{ srv.area }}">
                                    </div>
                                  </div>
                                    <div class="form-group">
                                    <label for="id_user" class="col-sm-2 control-label">用户名</label>
                                    <div class="col-sm-10">
                                      <input type="text" class="form-control" id="id_user" name="user" placeholder="用户名" value="{{ srv.user }}">
                                    </div>
                                  </div>
                                    <div class="form-group">
                                    <label for="id_password" class="col-sm-2 control-label">密码</label>
                                    <div class="col-sm-10">
                                      <input type="password" class="form-control" id="id_password" name="password" placeholder="密码（不填写表示已经连接）">
                                    </div>
                                  </div>
                                <div class="form-group">
                                    <label for="id_port" class="col-sm-2 control-label">端口</label>
                                    <div class="col-sm-10">
                                      <input type="password" class="form-control" id="id_port" name="port" placeholder="端口">
                                    </div>
                                  </div>
{#                                    <div class="form-group">#}
{#                                    <label for="id_bandwidth" class="col-sm-2 control-label">带宽</label>#}
{#                                    <div class="col-sm-10">#}
{#                                      <input type="text" class="form-control" id="id_bandwidth" name="bandwidth" placeholder="带宽" value="{{ srv.bandwidth }}">#}
{#                                    </div>#}
{#                                  </div>#}
{#                                    <div class="form-group">#}
{#                                    <label for="id_monitor" class="col-sm-2 control-label">监控</label>#}
{#                                    <div class="col-sm-10">#}
{#                                      <input type="text" class="form-control" id="id_monitor" name="monitor" placeholder="监控" value="{{ srv.monitor }}">#}
{#                                    </div>#}
{#                                  </div>#}
                                     <div class="form-group">
                                    <label for="id_remark" class="col-sm-2 control-label">备注</label>
                                    <div class="col-sm-10">
                                      <textarea id="id_remark" class="form-control" rows="3" name="remark">{{ srv.remark }}</textarea>
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                      <button type="submit" class="btn btn-primary">{% if srv %}更新{% else %}添加{% endif %}Server</button>
                                    </div>
                                  </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
{% endblock %}
{% block script %}
    <script>
    function validate(){
        var $inner_ip = $("input[name='inner_ip']");
        var $outer_ip = $("input[name='outer_ip']");
        if($inner_ip.val() == "" && $outer_ip.val() == ""){
            alert("内网IP和外网IP必须填写一项！");
            return false;
        }
    }
    </script>
{% endblock %}

templates/server/upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}配置管理系统_V1.0.0{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.css" %}">
{% endblock %}

{% block body %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Server列表
{#                    <small>控制面板</small>#}
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                    <li><a href="{% url 'server:index' %}"><i class="fa fa-dashboard"></i> Server列表</a></li>
                    <li class="active">资源导入</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">Server数据导入</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">

                                <form id="server_upload" action="{% url 'server:upload' %}" method="post" enctype="multipart/form-data">
                                    <div id="tips"></div>

                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="exampleInputFile">上传Server数据</label>
                                        <input type="file" id="id_upload_file" name="upload_file">
                                        <p class="help-block">请选择Server数据文件(仅支持CSV格式)
                                            <a href="{% static 'templates/server_template.csv' %}">点击下载Server导入模板</a></p>
                                      </div>
{#                                    <input type="file" name="file_upload" id="file_upload"/>#}
{#                                    <input type="submit" class="btn btn-default" value="上传" id="upload_submit"/>#}
                                    <input type="button" class="btn btn-primary" value="上传" id="upload_submit"/>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->

{% endblock %}
{% block script %}
    <script src="{% static "admin_lte/plugins/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "js/ajaxfileupload.js" %}"></script>
    <script src="{% static "admin_lte/plugins/datatables/dataTables.bootstrap.min.js"%}"></script>
    <script>
    function upload_error(message){
        $("#tips").html('<div class="alert alert-danger"><strong>错误：</strong>' + message + '</div>');
    }
    function upload_success(message){
        $("#tips").html('<div class="alert alert-success"><strong>恭喜：</strong>' + message + '</div>');
    }
    function upload_process(){
        $("#tips").html('<div class="alert alert-info"><strong>请稍候：</strong>文件正在上传...</div>');
    }


    $(function(){
        $("#server_upload").delegate("input[type='file']", "change", function(){
            $("#tips").empty();
        });

        $("#upload_submit").click(function(){
            if(!$("#id_upload_file").val()){
                upload_error("请选择CSV文件上传！");
                return false;
            }
            upload_process();
            $.ajaxFileUpload ({
                url :'{% url 'server:upload' %}',
                fileElementId :"id_upload_file",
                //secureuri,　　　　　　　 //是否启用安全提交，默认为false。
                dataType: "text",
                //服务器返回的数据类型。可以为xml,script,json,html。如果不填写，jQuery会自动判断。
                data:{"csrfmiddlewaretoken": $.cookie("csrftoken")},
                success :function(data){ //提交成功后自动执行的处理函数，参数data就是服务器返回的数据。
                    data = $.parseJSON($(data).text());
                    if(data.result == true){
                        upload_success(data.message);
                    }else{
                        upload_error(data.message);
                    }
                },
                error :function(e){ //提交失败自动执行的处理函数。
                    upload_error("文件上传失败！请检查网络连接。")
                }
            });
        });

    })
    </script>
{% endblock %}